[build]
builder = "nixpacks"

[deploy]
startCommand = "cd FastAPI_Classifier && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10


